### ISSUE TITLE
Handle Bad Files in GET Requests

### ISSUE THREAD

**Issue by hreineck** [EasyDynamics/oscal-rest-service#101]
As a user of the OSCAL Rest Service that is accessing local files, I want a more lenient system for accessing my OSCAL files.

Currently, a user of the OSCAL Rest Service that is setting up a local environment is expected to create an OSCAL content directory with a specific directory structure (see the [all-in-one deployment README](https://github.com/EasyDynamics/oscal-editor-deployment/tree/main/all-in-one)). The directory structure is simple enough, but if a user includes any files that are not properly formatted OSCAL JSON files, a 500 error is given with little feedback to the user.

There are several ways this can occur:
- A non-JSON file is included in one of the OSCAL file directories
- A directory exists within one of the OSCAL file directories
- The user tries to GET an improperly formatted OSCAL object

### Acceptance Criteria
- If a directory or non-JSON file exists in the `catalogs`, `component-definitions`, `profiles`, or  `system-security-plans` directories (or their equivalents, if renamed by the user), a corresponding GET request (eg. `GET localhost:1234/oscal/v1/system-security-plans`) ignores those files and does not return a 500 error.
- If an improperly formatted OSCAL JSON file is requested (such that would cause a 500 error), a more descriptive error is provided to the user that points out which file is incorrect, and if possible, what the original parsing error was.

### Implementation Notes

 - Test files to reproduce should be added to a repository of OSCAL content used purely for testing

**Comment by laurelmay** [comment]
This is actually really interesting because I know (uhh well now I feel like maybe just think) that I've seen the service ignore `README.md` files and other types. So it is interesting that it seems like _some_ files result in a 500 but others don't. I wonder if some of the workarounds that we had to do in #50 are causing us to be a little too fragile and not hitting the "non-OSCAL content" check. But even still, 500ing on directories and improperly structured OSCAL is a problem.

Hopefully this is just some fixes to `findAll` but we may need to do better about handling the related errors correctly throughout the stack (logging vs continuing to throw) or perhaps using Advice like we've done elsewhere for exceptions.

https://github.com/EasyDynamics/oscal-rest-service/blob/9be377026361c58615301ff56eb9848fd8482bd3/oscal-data-repository-file/src/main/java/com/easydynamics/oscal/data/repository/file/BaseOscalRepoFileImpl.java#L212-L236 

Additionally, we need to be careful about how we define "a more descriptive error is provided to the user". This very likely should be a log message and not data that is sent over the HTTP response.  We don't want to get into a habit of sending debugging info about server-side errors over the wire. Perhaps detail this is too technical for an AC but I think we can solve the same problem by more clearly defining "user" for the purpose of this ticket; possibly in this case we want to think of the user as someone deploying/managing/operating the OSCAL Rest Service?

**Comment by rgauss** [comment]
> I've seen the service ignore `README.md` files and other types

Yes, and the tests are using [oscal-demo-content](https://github.com/EasyDynamics/oscal-demo-content) which intentionally includes a `README.md` in the [SSPs folder](https://github.com/EasyDynamics/oscal-demo-content/tree/main/system-security-plans).

@hreineck, do you have more detail on specific files or scenarios where this is occurring?

**Comment by hreineck** [comment]
> > I've seen the service ignore `README.md` files and other types
> 
> Yes, and the tests are using [oscal-demo-content](https://github.com/EasyDynamics/oscal-demo-content) which intentionally includes a `README.md` in the [SSPs folder](https://github.com/EasyDynamics/oscal-demo-content/tree/main/system-security-plans).
> 
> @hreineck, do you have more detail on specific files or scenarios where this is occurring?

Specifically, this happens when I run the REST service in the all-in-one Docker deployment and I include a random file in the `oscal-content/system-security-plans` directory. When I try to open the SSP tab of the OSCAL Editor (which is running from the Docker container at localhost:8080), it gives the 500 error.
This file can be named anything as far as I can tell; as long as it is not formatted  as  JSON file with a `system-security-plan` root object, it gives a 500 error. 

The REST Service shows this error:
![image](https://user-images.githubusercontent.com/43356777/176770965-8447b0b0-5e1e-4e1b-a43b-49bdfa3079d4.png)
The relevant bit seems to be `failed to find root field`.

And network tools on the browser shows that the 500 is a response to a GET request at `http://localhost:8080/oscal/v1/system-security-plans`

A 500 also occurs if there is a sub-directory within `oscal-content/system-security-plans`, in which the REST service outputs the error `Is a directory`:
![image](https://user-images.githubusercontent.com/43356777/176771353-f285cd1b-28ad-4dcc-bf52-560d521d5663.png)

In both cases, the OSCAL Editor gives this standard error message:
![image](https://user-images.githubusercontent.com/43356777/176771504-29b0f513-1945-4aad-9480-e0a80a0716d4.png)

**Comment by laurelmay** [comment]
Okay so looking into this a bit, I think we can actually solve this in `getValidedPathContents()`. `File.listFiles()` has an overload that accepts a `FileFilter`. At least to ignore directories, we can do:

```java
File[] pathContents = pathFile.listFiles(File::isFile);
```

but then we mostly end up still accepting otherwise invalid files. But I also don't know that inserting that logic into the `FileFilter` is entirely appropriate. Anything we do there is likely to be less-than-perfect because it would be hard to base it on the behavior of the `liboscal-java` load logic.

So I also feel like in `findAll()` we just remove the `if`/`else`. We shouldn't just crash because there's something there that we can't parse. I think we should just silently (to the end user, but as a debug/info message to the server logs) skip that particular file as a return value. Now this means that if something wonky happens to the file (somehow we serialize invalid data) the end user may not be able to retrieve it. For today's model where we expect the service is semi-local to the end user (in a Docker container on the same host/network), I think this may be acceptable. Fundamentally, bad OSCAL, random JSON, or a README file are all going to be mostly the same to the API (they'd be an invalid response). And it's probably better for a list operation to return at least as much as we can to the user (of course, I'd have different opinions for other types of operations). This means, in my opinion, `findAll` should not directly through a `DataRetrievalFailureException` because at the end of the day, it's not really worth crashing over at this point.

If we want to support nested directories, I think we should open a feature request to support that feature outside of this immediate bug report.

**Comment by tuckerzp** [comment]
Using @kylelaker's suggestions to ignore `dir` files and to not throw and exception when getting an `IOException` seems to be on the right track, but I wanted to hear your opinion on intended functionality. 

I've been trying to further test `findAll()` and have found that the functionality when loading multiple `OSCAL Objects` when one has a parsing error is strange. `findAll()` returns all files that are considered parsable, even if they are not technically valid (like changing the `components` field to `componetz`). Once you try to view them in the editor, it seems that all of the `OSCAL objects` display `Yikes! Something went wrong loading the OSCAL data.` after loading an invalid object.  This warning persists regardless of you trying to load another object of the same type or switching to and from `REST` mode. 

I am unsure if that is something that is an issue due to how `findAll()` returns even invalid `OSCAL Objects`, with how the `React Library` handles loading between modes and files, or a combination of both.

**Comment by laurelmay** [comment]
> Once you try to view them in the editor, it seems that all of the `OSCAL objects` display `Yikes! Something went wrong loading the OSCAL data.` after loading an invalid object. This warning persists regardless of you trying to load another object of the same type or switching to and from `REST` mode.

This is an issue with `oscal-react-library`. Specifically, the way the `ErrorBoundary` is handled (and the state surrounding it). I've been meaning to write something up on this but was waiting until I sorta understood the problem more; I think I should just go ahead and do my best at this point though. I will open a Bug there. FWIW, you can reproduce in the Viewer by putting in an invalid URL -- entering a valid URL never "fixes" it unless you reload the whole page.

**Edit**: See EasyDynamics/oscal-react-library#489 and EasyDynamics/oscal-react-library#490

**Comment by laurelmay** [comment]
> I am unsure if that is something that is an issue due to how `findAll()` returns even invalid `OSCAL Objects`

To be clear though, if this is in fact happening, that is a problem and needs to be fixed. The service must never return bad data (but should also not crash because it is present).
